language: bash
sudo: false

language: elixir

matrix:
  include:
    - elixir: 1.6.4
      otp_release: 19.3
    - elixir: 1.6.4
      otp_release: 20.3

script:
  - "MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis"
